blog/blueprint.py
from flask import Blueprint, render_template, redirect, url_for, send_from_directory
from models import Post, Categories

from flask import request
from forms import Post_form
from app import db, app
from flask_security import login_required

from flask_ckeditor import upload_success, upload_fail
import os
# upload image prevu
from werkzeug.utils import secure_filename


def allowed_file(filename):
    ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'])
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


blog = Blueprint('blog',
                 __name__,
                 template_folder='templates',
                 static_folder='static', )


@blog.route('/files/<filename>')
def uploaded_files(filename):
    return send_from_directory(app.config['UPLOADED_PATH'], filename)


@app.route('/upload', methods=['POST'])
def upload():
    f = request.files.get('upload')
    extension = f.filename.split('.')[1].lower()
    if extension not in ['jpg', 'gif', 'png', 'jpeg']:
        return upload_fail(message='Image only!')
    f.save(os.path.join(app.config['UPLOADED_PATH'], f.filename))
    url = url_for('blog.uploaded_files', filename=f.filename)
    return upload_success(url=url)


@blog.route('/uploads/<filename>')
def send_file(filename):
    return send_from_directory(app.config['UPLOADED_PATH'], filename)


@blog.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    form = Post_form()
    if form.validate_on_submit():
        file = request.files['file']
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(app.config['UPLOADED_PATH'], filename))
        new_post = Post(title=form.title.data, body=form.body.data, link_image=filename)
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('blog.index'))
    return render_template('/create_post.html', form=form)


@blog.route('/<slug>/edit/', methods=['GET', 'POST'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()

    if request.method == 'POST':
        form = Post_form(fromdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('blog.post_detail', slug=post.slug))

    form = Post_form(obj=post)
    return render_template('/edit_post.html', post=post, form=form)


@blog.route('/')
def index():
    q = request.args.get('q')
    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    # Поиск
    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
    else:
        posts = Post.query.order_by(Post.id.desc())

    # Если мы пользуемся поиском posts будет списком постов
    pages = posts.paginate(page=page, per_page=3)
    return render_template('blog.html', posts=posts, pages=pages)


@blog.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    return render_template('post_detail.html', post=post)


# Делаем вьюху категории
# Не используется не в одном шаблоне
# Шаблон ещё даже не создан (можно переделать главный шаблон)
@blog.route('/categories/<slug>')
def categories_detail(slug):
    categorie = Categories.query.filter(Categories.slug == slug).first_or_404()
    posts = categorie.posts.all()
    return render_template('tag_detail.html', categorie=categorie, posts=posts)

parser/blueprint.py
from flask import Blueprint, render_template, flash, redirect, jsonify, json, url_for, session
from forms import FullForm, P_Form, Yy_form, DemoForm
from flask import request

from stoimost import order_stoimost
from decimal import Decimal

from models import Order
from app import db, q
from emails import send_new_email
from full_parser import main
from demo_parser import demo_main

import hashlib

parsers = Blueprint('parser', __name__, template_folder='templates', static_folder='static')


@parsers.route('', methods=['GET', 'POST'])
def parser():
    form = FullForm(request.form)
    p_form = P_Form()
    if form.validate():
        if request.method == 'POST' and request.form['pay_btn'] == 'Расчитать стоимость':
            ref = request.form['url_avito']
            limit = request.form['limit']

            ### Чек боксы ###
            contact_face = form.contact_face.data  # Контактное лицо
            ad_title = form.ad_title.data  # Заголовок объявления
            ad_description = form.ad_description.data  # Описание объявления
            ad_price = form.ad_price.data  # Цена объявления
            city = form.city.data  # Город
            address = form.address.data  # Район, метро, адрес
            ad_link = form.ad_link.data  # Ссылка на объявление

            session['checkbox'] = {
                'contact_face': contact_face,
                'ad_title': ad_title,
                'ad_description': ad_description,
                'ad_price': ad_price,
                'city': city,
                'address': address,
                'ad_link': ad_link
            }

            result = (order_stoimost(ref))
            p = Decimal(result[0])
            price = p.quantize(Decimal("1.00"))
            kol_vo_ob = result[-1]

            flash('{}'.format(price, kol_vo_ob))

            return render_template('parser/parser_full.html', form=form, price=price, kol_ob=kol_vo_ob, p_form=p_form)

        elif request.method == 'POST' and request.form['pay_btn'] == 'Оплатить заказ':
            ref = request.form['url_avito']
            limit = request.form['limit']

            result = (order_stoimost(ref))
            p = Decimal(result[0])
            price = p.quantize(Decimal("1.00"))
            kol_vo_ob = result[-1]
            email = request.form['email']
            pay_select = request.form['pay_select']
            type_file = request.form['type_file']

            # Прайс с комиссией
            commision_price = None
            if pay_select == '1':
                """ Банковская карта """
                commision_price_dem = price / 100 * 2 + price
                pr = Decimal(commision_price_dem)
                commision_price = pr.quantize(Decimal("1.00"))  # Цена с учетом комисии
                pay = 'Банковская карта (комиссия 2%)'
                pay_type = 'AC'
            elif pay_select == '2':
                """ Яндекс деньги """
                commision_price_dem = float(price) / 100 * 0.5 + float(price)
                pr = Decimal(commision_price_dem)
                commision_price = pr.quantize(Decimal("1.00"))
                pay = 'Яндекс.Деньги (комиссия 0,5%)'
                pay_type = 'PC'

            session['data'] = {'k': kol_vo_ob,  # Количество объявлений
                               'price': float(price),  # Стоимость без комисии
                               'commision_price': float(commision_price),  # Стоимость с комисией
                               'pay': pay,  # Способ оплаты
                               'email': email,
                               'ref': ref,
                               'pay_type': pay_type,
                               'type_file': type_file,}

            # Заносим заказ в бд
            try:
                order = Order(ref=ref,
                              email=email,
                              price=str(commision_price),
                              ad_title=form.contact_face.data,
                              ad_price=form.ad_price.data,
                              contact_face=form.contact_face.data,
                              ad_description=form.ad_description.data,
                              city=form.city.data,
                              address=form.address.data,
                              ad_link=form.ad_link.data,
                              type_file=type_file,
                              )
                db.session.add(order)
                db.session.commit()
            except:
                None
                # print('sdf')

            # print(float(price))
            # return render_template('parser/parser_full.html', form=form, price=price, kol_ob=kol_vo_ob)
            # return json.dump({'price': int(price)})
            # return render_template('parser/modal.html', k=kol_vo_ob, price=price, commision_price=commision_price, pay=pay,
            # email=email)
            return redirect(url_for('parser.pay'))


    else:
        return render_template('parser/parser_full.html', form=form)


# return 'OK'


@parsers.route('/pay', methods=['GET', 'POST'])
def pay():
    data = session.get('data')
    checkbox = session.get('checkbox')
    form = Yy_form

    # orders = Order.query.all()[-1]
    ordd = Order.query.filter(Order.email == data['email'])[-1]
    # print(order.id)
    # orders = Order.query.filter(Order.ref == data['ref']).first()
    # send_new_email(orders)  # Выполняет отправку почты
    # return 'OKs'
    if request.method == 'GET' and ordd.pay_status == True:
        return redirect('http://avito-parser24.ru/orders/' + ordd.slug)
    return render_template('parser/modal.html', order=ordd, form=form, k=data['k'], price=data['price'],
                           commision_price=data['commision_price'],
                           pay=data['pay'], email=data['email'], pay_type=data['pay_type'])


@parsers.route('/pay_verification', methods=['POST'])
def pay_verification():
    if request.method == 'POST':
        # z = request.data['label']
        # print(z)
        # print('Yvedomlenie prishlo')
        s = request.get_data()
        # print(s)
        lab = request.form['sha1_hash']
        # print(lab)
        notification_type = request.form['notification_type']
        operation_id = request.form['operation_id']
        amount = request.form['amount']
        currency = request.form['currency']
        datetime = request.form['datetime']
        sender = request.form['sender']
        codepro = request.form['codepro']
        notification_secret = 'azJ7LW0O0Bw4zS2L7RDTtXAl'
        label = request.form['label']
        sha1_hash = request.form['sha1_hash']

        sha1_str = notification_type + '&' + operation_id + '&' + amount + '&' + currency + '&' + datetime + '&' + sender + '&' + codepro + '&' + notification_secret + '&' + label
        sha1 = hashlib.sha1(sha1_str.encode('utf-8')).hexdigest()

        if sha1_hash == sha1:
            order = Order.query.filter(Order.id == int(label)).first()
            # print(order.id)
            # order = Order.query.get(int(label))
            # Запускаем задачу в редис
            j = q.enqueue(main, order.ref, order.ad_title, order.ad_price, order.contact_face, order.ad_description,
                          order.city,
                          order.address, order.ad_link, order.type_file)
            id_worker = j.get_id()  # Узнаем id процесса
            # order_new = order(pay_status=True, id_worker=id_worker)
            order.pay_status = True
            order.id_worker = id_worker
            db.session.add(order)
            db.session.commit()

            send_new_email(order)  # Выполняет отправку почты
            return 'HTTP 200 OK'
    return 'HTTP 200 OK'
    #  Тут начинаем передачу задачи в редис


# ha = hashlib.sha1(b'Hello Python').hexdigest()

@parsers.route("/demo_parser", methods=['GET', 'POST'])
def demo_parser():
    form = DemoForm(request.form)
    if request.method == 'POST' and form.validate():
        ref = request.form['url_avito']
        email = request.form['email']

        ### Чек боксы ###
        contact_face = form.contact_face.data  # Контактное лицо
        ad_title = form.ad_title.data  # Заголовок объявления
        ad_description = form.ad_description.data  # Описание объявления
        ad_price = form.ad_price.data  # Цена объявления
        city = form.city.data  # Город
        address = form.address.data  # Район, метро, адрес
        ad_link = form.ad_link.data  # Ссылка на объявление

        type_file = request.form['type_file']

        # Запускаем процес в редис
        j = q.enqueue(demo_main,
                      ref,
                      ad_title,
                      ad_price,
                      contact_face,
                      ad_description,
                      city,
                      address,
                      ad_link,
                      type_file,
                      )

        id_worker = j.get_id()  # Узнаем id процесса
        try:
            order = Order(ref=ref, email=email, id_worker=id_worker, type_file=type_file)
            db.session.add(order)
            db.session.commit()
        except:
            None

        orders = Order.query.all()[-1]

        send_new_email(orders)  # Выполняет отправку почты

        flash('{}'.format(orders.id))  # Полезный способ показать сообщение пользователю.
        return render_template('parser/demo_parser.html', form=form, orders=orders)
    return render_template('parser/demo_parser.html', form=form)

blog/templates/blog.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">

    <title>Блог о поиске целевой аудитории</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" media="screen" href="{{ url_for('blog.static', filename='css/bootstrap.min.css') }}" />

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" media="screen" href="{{ url_for('blog.static', filename='css/blog-home.css') }}" />

    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter50436994 = new Ya.Metrika2({
                        id:50436994,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true,
                        webvisor:true
                    });
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = "https://mc.yandex.ru/metrika/tag.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks2");
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/50436994" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('blog.index') }}">Блог о поиске целевой аудитории</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('blog.index') }}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('parser.parser') }}">Прасер</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

          <h1 class="my-4">Блог о поиске целевой аудитории
          </h1>
          {% block content %}
          {% for post in pages.items %}
          <!-- Blog Post -->
          <div class="card mb-4">
            <img class="card-img-top" src="{{ url_for('blog.uploaded_files', filename=post.link_image) }}" alt="Card image cap" width="750" height="300">
            <div class="card-body">
              <h2 class="card-title">{{ post.title }}</h2>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
              <a href="{{ url_for('blog.post_detail', slug=post.slug) }}" class="btn btn-primary">Читать &rarr;</a>
            </div>
          </div>
           {% endfor %}

          <!-- Pagination -->
          <ul class="pagination justify-content-center mb-4">
            <li {% if not pages.has_prev %} class="page-item disabled" {% endif %}>
              <a class="page-link" href="./?page={{ pages.pref_num }}">&larr; Назад</a>
            </li>
            <li {% if  pages.has_prev %} class="page-item disabled" {% endif %}>
              <a class="page-link" href="./?page={{ pages.next_num }}">Вперед &rarr;</a>
            </li>
          </ul>

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Поиск</h5>
            <form class="card-body" method="get">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for..." name="q" value="{{ request.args.get('q', '') }}">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="submit">Go!</button>
                </span>
              </div>
            </form>
          </div>
          {% endblock %}
        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">© Copyright by Avito-Parser24.ru</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for('blog.static', filename='js/jquery.min.js') }}"> </script>
    <script src="{{ url_for('blog.static', filename='js/bootstrap.bundle.min.js') }}"> </script>

  </body>

</html>

blog/templates/edit_post.html
<!DOCTYPE html>
<html lang="ru">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">

    <title>Blog Home - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-home.css" rel="stylesheet">

  </head>

  <body>
    {% block content %}
        <form action="{{ url_for('blog.edit_post', slug=post.slug) }}" method="post">
            <div class="warpper" style="width: 700px; margin: auto">

                {{ form.csrf_token }}
                {{ form.title.label }}<br>
                {{ form.title }}<br><br>
                {{ form.body.label }}<br>
                {{ form.body }}
                <br>
                {{ form.submit }}

	        </div>
    {{ ckeditor.load() }}
	{{ ckeditor.config(name='body') }}
        </form>
    {% endblock %}

  </body>

</html>

blog/templates/html test.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">

    <title>Blog Home - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-home.css" rel="stylesheet">

    <!----------------------------------------------------------->

          <!-- include libraries(jQuery, bootstrap) -->
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script>

    <!-- include summernote css/js -->
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>

  </head>

  <body>
    {% block content %}
        <form action="{{ url_for('blog.create_post') }}" method="post">
            <div class="row form-group d-flex justify-content-center">
                {{ form.title.label(class="col-md-2") }}
                <div class="col-md-9">
                    {{ form.title(class="col-md-6 form-control") }}
                </div>
            </div>
            <div class="row form-group d-flex justify-content-center">
                {{ form.body.label(class="col-md-2") }}
                <div class="col-md-9">
                    {{ form.body(class="col-md-6 form-control") }}
                </div>
            </div>
            <button type="submit" class="btn btn-primary col-md-2">Создать пост</button>
        </form>
    {% endblock %}

  </body>

</html>

blog/templates/post_detail.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{{ post.title }}">
    <meta name="author" content="">

    <title>{{ post.title }}</title>

     <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" media="screen" href="{{ url_for('blog.static', filename='css/bootstrap.min.css') }}" />

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" media="screen" href="{{ url_for('blog.static', filename='css/blog-post.css') }}" />

    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter50436994 = new Ya.Metrika2({
                        id:50436994,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true,
                        webvisor:true
                    });
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = "https://mc.yandex.ru/metrika/tag.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks2");
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/50436994" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('blog.index') }}">Блог о поиске целевой аудитории</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('blog.index') }}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('parser.parser') }}">Прасер</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://avito-parser24.ru/#advantages">Наши приемущества</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->

          <h1 class="mt-4">{{ post.title }}</h1>

          <!-- Preview Image -->
          <img class="img-fluid rounded" src="{{ url_for('blog.uploaded_files', filename=post.link_image) }}" alt="" width="900" height="300">

          <hr>
          <!-- Post Content -->

          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>
          <p>{{ post.body }}</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
          <hr>
          {{ post.body|safe }}
          <!-- Comments Form -->
          <div class="card my-4">
            <h5 class="card-header">Оставить коментарий:</h5>
            <div class="card-body">
              <form>
                <div class="form-group">
                  <input class="form-control" type="text" placeholder="Введите ваше имя">
                  <textarea class="form-control" rows="3" placeholder="Текст отзыва"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>

          <!-- Single Comment -->
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
          </div>

          <!-- Comment with nested comments -->
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

              <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                  <h5 class="mt-0">Commenter Name</h5>
                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
              </div>

              <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                  <h5 class="mt-0">Commenter Name</h5>
                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
              </div>

            </div>
          </div>

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

           <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <form class="card-body" method="get">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for..." name="q" value="{{ request.args.get('q', '') }}">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="submit">Go!</button>
                </span>
              </div>
            </form>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">Web Design</a>
                    </li>
                    <li>
                      <a href="#">HTML</a>
                    </li>
                    <li>
                      <a href="#">Freebies</a>
                    </li>
                  </ul>
                </div>
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">JavaScript</a>
                    </li>
                    <li>
                      <a href="#">CSS</a>
                    </li>
                    <li>
                      <a href="#">Tutorials</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <!-- Side Widget -->
          <div class="card my-4">
            <h5 class="card-header">Side Widget</h5>
            <div class="card-body">
              You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
            </div>
          </div>

        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
      </div>
      <!-- /.container -->
    </footer>

   <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for('blog.static', filename='js/jquery.min.js') }}"> </script>
    <script src="{{ url_for('blog.static', filename='js/bootstrap.bundle.min.js') }}"> </script>

  </body>

</html>